# Generated by Django 5.2.6 on 2025-09-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=0)),
                ('local', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('carencia', models.IntegerField(default=0)),
            ],
        ),
    ]
