# Generated by Django 5.2.6 on 2025-09-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_movimentacao_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='saidas',
            name='destino',
            field=models.CharField(default='Não especificado', help_text='Para onde o produto será destinado', max_length=200),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='destino',
            field=models.CharField(default='Não especificado', help_text='Para onde o produto será destinado', max_length=200),
        ),
    ]
