# Generated by Django 5.2.6 on 2025-11-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_nome_alter_customuser_sobrenome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sobrenome',
        ),
    ]
