# Generated by Django 5.2.6 on 2025-11-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_customuser_nome_remove_customuser_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telefone',
        ),
    ]
