# Generated by Django 5.2.6 on 2025-11-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_customuser_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='logs',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='saidas',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='aprovador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.CharField(max_length=150),
        ),
    ]
