# Generated by Django 5.2.6 on 2025-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_entradas_usuario_alter_logs_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='politicas_privacidade_aceitas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='termos_uso_aceitos',
            field=models.BooleanField(default=False),
        ),
    ]
